<!DOCTYPE html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Login Form</title>
  <link rel="stylesheet" href="<?php echo URL.'/css/style.css'?>">
</head>
<body>
  <section class="container">
    <div class="login">
      <h1>Login</h1>
      <form method="post" action="/user/login">
        <p><input type="text" name="username" value="" id="username" placeholder="Username" required=""></p>
        <p><input type="password" name="password" value="" id="password" placeholder="Password" required=""></p>
        <p class="submit"><input type="submit" name="login" id="login" value="Log in"></p>
      </form>
    </div>

  </section>
</body>
</html>
